### ISSUE TITLE
Not working on Edge and Safari

### ISSUE THREAD

**Issue by RobertvdWoude** [web-push-libs/web-push-csharp#101]
Solved it by removing netstandard1.3 support and added: 
            System.Net.ServicePointManager.SecurityProtocol = System.Net.ServicePointManager.SecurityProtocol | System.Net.SecurityProtocolType.Tls12 | System.Net.SecurityProtocolType.Tls11 | System.Net.SecurityProtocolType.Tls;
in 
        public async Task SendNotificationAsync(PushSubscription subscription, string payload = null,
            Dictionary<string, object> options = null, CancellationToken cancellationToken = default)
        {
            var request = GenerateRequestDetails(subscription, payload, options);
            System.Net.ServicePointManager.SecurityProtocol = System.Net.ServicePointManager.SecurityProtocol | System.Net.SecurityProtocolType.Tls12 | System.Net.SecurityProtocolType.Tls11 | System.Net.SecurityProtocolType.Tls;
            var response = await HttpClient.SendAsync(request, cancellationToken).ConfigureAwait(false);

            await HandleResponse(response, subscription).ConfigureAwait(false);
        }

**Comment by coryjthompson** [comment]
Thank you for the details. 

I wouldn't recommend this fix. You're allowing .NET to use TLS versions 1.0 and 1.1, both have known vulnerabilities.

Your environment must have an issue where TLS 1.2 isn't working correctly. This could be due to running an old version of windows. I would recommend sorting out this issue over using the fix above.
