### ISSUE TITLE
Bad Gateway 502

### ISSUE THREAD

**Issue by marsimoto03** [web-push-libs/web-push-csharp#46]
Hi!

I have an issues and a few questions in that regard. When using SendNotificationAsync() while sending around 5000 notifications sometime I get a WebPushException with http status code 502 Bad Gateway. Both from FCM and mozilla - i searched trough the documentation and could not find anything that useful. Does anybody know what I can do about it?
Is there a limit on the number of notifications they can process? But 5k seems not much to me.
Or is there a way to send notifications in a batch or should I better use SendNotification()?

As a side note I am on version 1.0.9 because with one of the newer versions a different System.Http version was targeted which I can not use - we use the one provided by the framework itself and ran into errors using version 1.0.11 of this library.

Thanks for any help!
Greetings, Julian

**Comment by tuwrraphael** [comment]
5000 HTTP Post requests should not be a problem for the HttpClient; No matter if you call it synchronously or asynchronously. However I am not an expert on this topic.

As far as I understood, it is up to the push server (browser manufactorer) to reject push notifications, for example to filter spam, and the more "un-spam-like" your notification behaviour is, the more likely is that they get delivered.

Web push notifications should be
> Timely, Relevant, and Precise (https://developers.google.com/web/fundamentals/push-notifications/)

in other words, it should be a short information targetted to a specific user, and it should reach the user in the right moment. Therefore also no broadcast capability is included in the standard.

Recently, I discussed the following case: A specific feature of a platform was under maintainance for some hours. The request was to inform all the users of the platform via web push that the feature is back online.
I suggested to provide a method for the user  to request the notification instead of informing all the users. Like when a user tries to use an unavailable feature, some text explains that its currently under maintainance next to a button "inform me when available".
This has the adventage that  other users don't feel "spammed", while the user who's waiting for the functionality is informed in the right moment, that its up again. A side effect is that users who didn't try to access the platform during that time did not even notice that it was unavailable.

**Comment by coryjthompson** [comment]
502 bad gateway:
`The server was acting as a gateway or proxy and received an invalid response from the upstream server.`

As far as I can tell this would imply a temporary outage of the providers end. If a bad request was sent or you were being rate limited, i would expect a different response code (400, 429).

**Comment by marsimoto03** [comment]
Thanks for the insight!
Today I got a 406 error code from edge / windows push notification service. The code says:

> The cloud service exceeded its throttle limit. Log the details of your request. Reduce the rate at which you are sending notifications.

Does anyone know which rate is acceptable for edge?
