### ISSUE TITLE
support for safari

### ISSUE THREAD

**Issue by erionalite** [web-push-libs/web-push-csharp#49]
I have a hard requirements to implement web push notifications. Do we know if there any blockers to make web push work with safari, and Edge ?

**Comment by tuwrraphael** [comment]
I tested this package successfully together with Edge.
Version
Microsoft Edge 42.17134.1.0
Microsoft EdgeHTML 17.17134

**Comment by aatmmr** [comment]
Web Push Notifications for Safari are a different story compared to the Push API, i.e. Apple does comply with the Web Push Protocol that this library covers. For info how to make browser push notifications work with Safari (macOS only!) see [Apples Developer Docs](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/NotificationProgrammingGuideForWebsites/PushNotifications/PushNotifications.html#//apple_ref/doc/uid/TP40013225-CH3-SW1).

Otherwise, I can confirm that the library works with the supported browsers from ASP.NET Core including Edge. For supporting browsers see [Can I Use Push API](https://caniuse.com/#search=Push%20API).

**Comment by coryjthompson** [comment]
As mentioned unless Safari implement the push api - this library will not work for Safari.

It should however work with Edge and I will update the read me.

Thanks @aatmmr and @tuwrraphael

**Comment by CiceuBogdan** [comment]
@coryjthompson Hi. Support for Push API has been added on Safari 16.1 [Can I Use Push API](https://caniuse.com/#search=Push%20API). I see that in [NodeJs library](https://github.com/web-push-libs/web-push#browser-support) support has been added. Can you reopen this issue and maybe someone will take this in the following days? thanks a lot
