### ISSUE TITLE
Please add support for new MS Edge chromium

### ISSUE THREAD

**Issue by Guru-Soft** [web-push-libs/web-push-csharp#65]
Hi, 
I tried the code with new MS Edge chromium v80.0.361.33 beta 64-bit. 
I am getting BadRequest error

However, it works well with chrome Version 77.0.3865.90 (Official Build) (64-bit)
Please add support for new MS Edge chromium

Also, the below sample works correctly on both the browsers mentioned above:
https://gauntface.github.io/simple-push-demo/

**Comment by AndreasAmMueller** [comment]
Just saw this issue.   
I'm using the NuGet package on my application and it works with all current versions of Chrome, Firefox, Opera and also the new Edge based on Chromium - so I cannot confirm.

Tested with:
Microsoft Edge Version 81.0.416.58 (Offizielles Build) (64-Bit)

**Comment by phil-w** [comment]
See also '69

This is working fine for me with Firefox and Brave (latest versions), but I repeatibly Edge 
Version **87.0.664.75** (Official build) (64-bit)
fails with 401 not authorized. It's the same server code supposed to be sending the notifications etc.

Examining the different endpoints, the one with the problem is: 
https://db5p.notify.windows.com/w/?token=BQ...

It's odd because if I hit the end point immediately I set it up, it works, it's just if I try the same thing again later, it's "not authorized". I note there's a token in the end point... which is suspicious. 

The crude work-around would be to delete the end point and recreate it every time I need to notify any Edge end points (!), but presumably there's an obvious reason for this. I'll look at your code...

**Comment by phil-w** [comment]
I had this issue but it was caused by me truncating endpoints in my database see issue #174 here. You need varchar(500).
